home_controller:
    resource: '../src/Controller'
    type: annotation

# config/routes.yaml
kernel:
    resource: '../src/Kernel.php'
    type: annotation


################TEST L'AMUSÉE############################

# Voir le test Front-End
homepage:
    path: /homepage
    controller: App\Controller\HomeController::homepage


 # Voir le test Back-end
Form:
    path: /Form
    controller: App\Controller\DownloadController::Form

##########################################################


